# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(504, 739)
        MainWindow.setMinimumSize(QtCore.QSize(504, 739))
        MainWindow.setMaximumSize(QtCore.QSize(504, 739))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txtUmbral = QtWidgets.QLineEdit(self.centralwidget)
        self.txtUmbral.setGeometry(QtCore.QRect(420, 80, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtUmbral.setFont(font)
        self.txtUmbral.setMaxLength(4)
        self.txtUmbral.setObjectName("txtUmbral")
        self.cbUsuariosRanking = QtWidgets.QComboBox(self.centralwidget)
        self.cbUsuariosRanking.setGeometry(QtCore.QRect(220, 30, 191, 22))
        self.cbUsuariosRanking.setEditable(False)
        self.cbUsuariosRanking.setObjectName("cbUsuariosRanking")
        self.lblPrediccion = QtWidgets.QLabel(self.centralwidget)
        self.lblPrediccion.setGeometry(QtCore.QRect(240, 640, 251, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblPrediccion.setFont(font)
        self.lblPrediccion.setText("")
        self.lblPrediccion.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblPrediccion.setObjectName("lblPrediccion")
        self.btnRecomendarPelicula = QtWidgets.QPushButton(self.centralwidget)
        self.btnRecomendarPelicula.setGeometry(QtCore.QRect(200, 580, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnRecomendarPelicula.setFont(font)
        self.btnRecomendarPelicula.setObjectName("btnRecomendarPelicula")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(260, 81, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.tbRanking = QtWidgets.QTableWidget(self.centralwidget)
        self.tbRanking.setGeometry(QtCore.QRect(10, 220, 481, 271))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tbRanking.setFont(font)
        self.tbRanking.setObjectName("tbRanking")
        self.tbRanking.setColumnCount(2)
        self.tbRanking.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbRanking.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbRanking.setHorizontalHeaderItem(1, item)
        self.btnRecomendarTabla = QtWidgets.QPushButton(self.centralwidget)
        self.btnRecomendarTabla.setGeometry(QtCore.QRect(200, 141, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnRecomendarTabla.setFont(font)
        self.btnRecomendarTabla.setObjectName("btnRecomendarTabla")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 520, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(60, 640, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.lblRanking = QtWidgets.QLabel(self.centralwidget)
        self.lblRanking.setGeometry(QtCore.QRect(220, 191, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblRanking.setFont(font)
        self.lblRanking.setObjectName("lblRanking")
        self.cbPeliculas = QtWidgets.QComboBox(self.centralwidget)
        self.cbPeliculas.setGeometry(QtCore.QRect(220, 520, 191, 22))
        self.cbPeliculas.setEditable(True)
        self.cbPeliculas.setObjectName("cbPeliculas")
        self.txtItemsRanking = QtWidgets.QLineEdit(self.centralwidget)
        self.txtItemsRanking.setGeometry(QtCore.QRect(180, 80, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtItemsRanking.setFont(font)
        self.txtItemsRanking.setMaxLength(2)
        self.txtItemsRanking.setClearButtonEnabled(False)
        self.txtItemsRanking.setObjectName("txtItemsRanking")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 30, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 81, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 504, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.txtUmbral.setText(_translate("MainWindow", "-1"))
        self.btnRecomendarPelicula.setText(_translate("MainWindow", "Predecir"))
        self.label_3.setText(_translate("MainWindow", "Umbral de similitud"))
        item = self.tbRanking.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Titulo"))
        item = self.tbRanking.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Prediccion"))
        self.btnRecomendarTabla.setText(_translate("MainWindow", "Recomendar"))
        self.label_6.setText(_translate("MainWindow", "Selecciona una pelicula"))
        self.label_7.setText(_translate("MainWindow", "Prediccion: "))
        self.lblRanking.setText(_translate("MainWindow", "Ranking"))
        self.txtItemsRanking.setText(_translate("MainWindow", "10"))
        self.label.setText(_translate("MainWindow", "Selecciona a un usuario"))
        self.label_2.setText(_translate("MainWindow", "Items del ranking"))

