# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(504, 623)
        MainWindow.setMinimumSize(QtCore.QSize(504, 623))
        MainWindow.setMaximumSize(QtCore.QSize(504, 623))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 511, 591))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(40, 40, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(40, 91, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(260, 91, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(220, 201, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.tbRanking = QtWidgets.QTableWidget(self.tab)
        self.tbRanking.setGeometry(QtCore.QRect(10, 230, 481, 271))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tbRanking.setFont(font)
        self.tbRanking.setObjectName("tbRanking")
        self.tbRanking.setColumnCount(3)
        self.tbRanking.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tbRanking.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbRanking.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbRanking.setHorizontalHeaderItem(2, item)
        self.btnRecomendarTabla = QtWidgets.QPushButton(self.tab)
        self.btnRecomendarTabla.setGeometry(QtCore.QRect(200, 151, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnRecomendarTabla.setFont(font)
        self.btnRecomendarTabla.setObjectName("btnRecomendarTabla")
        self.txtItemsRanking = QtWidgets.QLineEdit(self.tab)
        self.txtItemsRanking.setGeometry(QtCore.QRect(180, 90, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtItemsRanking.setFont(font)
        self.txtItemsRanking.setMaxLength(2)
        self.txtItemsRanking.setClearButtonEnabled(False)
        self.txtItemsRanking.setObjectName("txtItemsRanking")
        self.txtUmbral = QtWidgets.QLineEdit(self.tab)
        self.txtUmbral.setGeometry(QtCore.QRect(420, 90, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txtUmbral.setFont(font)
        self.txtUmbral.setMaxLength(4)
        self.txtUmbral.setObjectName("txtUmbral")
        self.cbUsuariosRanking = QtWidgets.QComboBox(self.tab)
        self.cbUsuariosRanking.setGeometry(QtCore.QRect(220, 40, 191, 22))
        self.cbUsuariosRanking.setEditable(False)
        self.cbUsuariosRanking.setObjectName("cbUsuariosRanking")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.cbUsuariosPelicula = QtWidgets.QComboBox(self.tab_2)
        self.cbUsuariosPelicula.setGeometry(QtCore.QRect(220, 40, 191, 22))
        self.cbUsuariosPelicula.setObjectName("cbUsuariosPelicula")
        self.label_5 = QtWidgets.QLabel(self.tab_2)
        self.label_5.setGeometry(QtCore.QRect(40, 40, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.cbPeliculas = QtWidgets.QComboBox(self.tab_2)
        self.cbPeliculas.setGeometry(QtCore.QRect(220, 90, 191, 22))
        self.cbPeliculas.setEditable(True)
        self.cbPeliculas.setObjectName("cbPeliculas")
        self.label_6 = QtWidgets.QLabel(self.tab_2)
        self.label_6.setGeometry(QtCore.QRect(40, 90, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.btnRecomendarPelicula = QtWidgets.QPushButton(self.tab_2)
        self.btnRecomendarPelicula.setGeometry(QtCore.QRect(200, 150, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btnRecomendarPelicula.setFont(font)
        self.btnRecomendarPelicula.setObjectName("btnRecomendarPelicula")
        self.label_7 = QtWidgets.QLabel(self.tab_2)
        self.label_7.setGeometry(QtCore.QRect(60, 210, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.lblPrediccion = QtWidgets.QLabel(self.tab_2)
        self.lblPrediccion.setGeometry(QtCore.QRect(240, 210, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblPrediccion.setFont(font)
        self.lblPrediccion.setText("")
        self.lblPrediccion.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblPrediccion.setObjectName("lblPrediccion")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 504, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Selecciona a un usuario"))
        self.label_2.setText(_translate("MainWindow", "Items del ranking"))
        self.label_3.setText(_translate("MainWindow", "Umbral de similitud"))
        self.label_4.setText(_translate("MainWindow", "Ranking"))
        item = self.tbRanking.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id. Item"))
        item = self.tbRanking.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Titulo"))
        item = self.tbRanking.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Prediccion"))
        self.btnRecomendarTabla.setText(_translate("MainWindow", "Recomendar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Ranking"))
        self.label_5.setText(_translate("MainWindow", "Selecciona a un usuario"))
        self.label_6.setText(_translate("MainWindow", "Selecciona una pelicula"))
        self.btnRecomendarPelicula.setText(_translate("MainWindow", "Predecir"))
        self.label_7.setText(_translate("MainWindow", "Prediccion: "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Pelicula"))

